### ISSUE TITLE
[Operation]: Chalisa Intermediate Representation (Timestamp to Source + Foundation Indexer)

### ISSUE THREAD

**Issue by KosmonautX** [ve1ld/vyasa#21]
### Present Context

<details>
<summary>Helping words...</summary>

Where we collectively investigate and interrogate the problem space and iteratively scope our approach.

Breakdown to landmarks that communicate shared context we are working towards through 2-tiered task list, CRUD list elements as development unfolds.

Strike the scope of code that reveals the most about the problem/solution FIRST not necessarily the easiest or hardest parts
```

```
---
</details>

- [ ] Intermediate Representation
    - [x]  OG Gulshan Kumar IR w Timestamps to Verse
      - [x] 	Create .srt from the captions data from youtube
      - [x] use some nlp lib to map the verses to the captions (via a common .srt file)
      - [ ] Improve the similarity function by increasing the level of granularity -- we can consider using morphemes for this 
    - [ ]  Jump Sync video player to verse
  
- [ ] Text Indexing 
    - [ ]  Text Schema for representation of verses
    - [ ]  Associating 2 target translation verses
    - [ ]  Associating 1 commentary verses
 
- [ ] Media associations with the source text (dependent) on IR and text indexing

### Groundwork

<details>
<summary> Helping words...</summary>

Introduce us to the problem space. Write out what you already know about the terrain you are the recce commander enriching us with details beyond the fog of war.

Where have you tried applying and encountered difficulties?

How have others attempted to scale or explore these challenges? 

(Embed internal & external links to related or possible  paths of exploration, stackoverflow, documentation, github etc)

Who should be notified?

Emphasis on previous or current practice to discover what is ugly, missing, or unnecessary.

</details>

[Downloading auto-generated YouTube transcriptions](https://webapps.stackexchange.com/a/31565)
[that which we bild](https://excalidraw.com/#room=cc37be8956ab78fb92d3,bBwSOK2h_An6-DiWZHv0Zw)

### Reflection

<details>
<summary> Helping words...</summary>
Where the eternal wheel returns back to practice and what we finally implemented is to be outlined. You are the historian or archivist bringing clarity to future-yous and us about your foray.

Emphasis on approaching timeless solutions for well-defined problem space through distillation by decanting that which is un-needed and abstracting that which is essential to approaching the problem space. 

Add any reflections and internal links to future potential and blindsides.

```
INPUT UR ANSWER HERE
```

</details>

**Comment by rtshkmr** [comment]
notes: 
1. IR: 
 - can just be json for now, it's just a need to pre-processed and stored as a IR 

2. Indexer is more of a intro to ecto

**Comment by rtshkmr** [comment]
### Creating .srt from the caption data 

[chalisa.json](https://github.com/ve1ld/vyasa/files/13943892/chalisa.json)


#### Observations: 
1. seems like bhajans will repeat certain stanzas, not sure how to account for that yet [for the mapping part]

**Comment by rtshkmr** [comment]
### Mapping Scraped Data to Autogenerated Data 

The goal here is to map the fixed-structured, perfect data to the correct part of the .srt file. 
Since we are working with .srt files, which naturally already have events that are indexed, a first pass of this for this is to just map each verse to the correct event index. 

In order to do this, we need to some sentence similarity matching. 
The underlying idea would be to use some sort of edit distances (jaccard, levenshtein) or other distance metrics like cosine distance.

After a quick check, it's better to use a recent library that supports indic texts for this first pass. 

Here are some candidates: 
1. [libindic/soundex](https://github.com/libindic/soundex)
2. [inltk](https://github.com/goru001/inltk) -- it's more recently updated and the library's stats are a little better.



--- 

unrelated but interesting stuff found:
1. there's a whole AI for bharat thing going on here -- https://ai4bharat.iitm.ac.in/areas/transliteration/

**Comment by rtshkmr** [comment]
###inltk



<details><summary>macos fails, linux seems to have outdated package name 😢 </summary>

![image](https://github.com/ve1ld/vyasa/assets/38996397/533d3ac4-833f-478a-8521-7a57eb06e589)



</details>
